// Generated by https://quicktype.io

export interface CalendarResponse {
  id: string;
  fullname: string;
  age: string;
  allVaccinesImplemented: AllVaccinesImplemented[];
  vaccinesNotAdministrated: VaccinesNotAdministrated[];
}

export interface AllVaccinesImplemented {
  id: string;
  nameVacune: string;
  month: number;
}

export interface VaccinesNotAdministrated {
  id: string;
  vacuneName: string;
  age: number;
}
